#define trigPin 1
#define echoPin 3
#define buzzerPin 7

int zmierzOdleglosc()
{
  long czas, dystans;
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);

  czas = pulseIn(echoPin, HIGH);
  dystans = czas / 58;

  return dystans;

}

void zakres(int a)
{
  int jak_daleko = zmierzOdleglosc();
  if(jak_daleko < a)
  {
    digitalWrite(buzzerPin, HIGH);
  }
  else 
  {
    digitalWrite(buzzerPin, LOW);
  }
}

void setup() {
  Serial.begin(9600);
  pinMode(buzzerPin, OUTPUT);
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);

}

void loop() {
  Serial.print(zmierzOdleglosc());
  Serial.println(" cm");
  zakres(10);
  delay(500);
}
